name: Hide and Hand
favicon: null
layout_spectrum: 0.08665216295048594
typography_spectrum: 0.4219183521345258
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5036779760848731
  lightness: 0.814183735055849
  saturation: 0.6235650992020965
  rhythmicContrast: 0.36375412880443037
purpose: []
