name: Hide and Hand
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4f2f3'
    - '#211c20'
    - '#e5ba85'
    - '#8f4c32'
    - '#817d7a'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6235650992020965
  rhythmicContrast: 0.5
purpose: []
